# Fall 2024 Data Science Track: Week 2 - Data Cleaning Exercise

## Packages, Packages, Packages!

Import *all* the things here! You need the standard stuff: `pandas` and `numpy`.

If you got more stuff you want to use, add them here too. 🙂

In [1]:
# Import here.
!pip install pandas numpy
import pandas as pd
import numpy as np

Requirement already satisfied: pandas in /usr/local/python/3.12.1/lib/python3.12/site-packages (3.0.5)
Requirement already satisfied: numpy in /usr/local/python/3.12.1/lib/python3.12/site-packages (2.5.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/codespace/.local/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /home/codespace/.local/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 26.0.1 -> 26.2.1
[notice] To update, run: python3 -m pip install --upgrade pip

## Introduction

With the packages out of the way, now you will be working with the following data sets:

* `food_coded.csv`: [Food choices](https://www.kaggle.com/datasets/borapajo/food-choices?select=food_coded.csv) from Kaggle
* `Ask A Manager Salary Survey 2021 (Responses) - Form Responses 1.tsv`: [Ask A Manager Salary Survey 2021 (Responses)](https://docs.google.com/spreadsheets/d/1IPS5dBSGtwYVbjsfbaMCYIWnOuRmJcbequohNxCyGVw/view?&gid=1625408792) as *Tab Separated Values (.tsv)* from Google Docs

Each one poses different challenges. But you’ll―of course―overcome them with what you learned in class! 😉

## Food Choices Data Set

### Load the Data

In [2]:
# Load the Food choices data set into a variable (e.g., df_food).

food_data_set_path = '/workspaces/ds-fall-2026/Week-02-Pandas-and-How-to-Make-a-Sick-Project/data/food_coded.csv'

df_food = pd.read_csv(food_data_set_path)

### Explore the Data

How much data did you just load?

In [10]:
# Count by hand. (lol kidding)
df_food.info()

<class 'pandas.DataFrame'>
RangeIndex: 125 entries, 0 to 124
Data columns (total 61 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   GPA                           123 non-null    str
 1   Gender                        125 non-null    int64
 2   breakfast                     125 non-null    int64
 3   calories_chicken              125 non-null    int64
 4   calories_day                  106 non-null    float64
 5   calories_scone                124 non-null    float64
 6   coffee                        125 non-null    int64
 7   comfort_food                  124 non-null    str
 8   comfort_food_reasons          123 non-null    str
 9   comfort_food_reasons_coded    106 non-null    float64
 10  cook                          122 non-null    float64
 11  comfort_food_reasons_coded.1  125 non-null    int64
 12  cuisine                       108 non-null    float64
 13  diet_current                  124 non-null    str
 14  diet_current_coded            125 non-null    int64
 15  drink                         123 non-null    float64
 16  eating_changes                122 non-null    str
 17  eating_changes_coded          125 non-null    int64
 18  eating_changes_coded1         125 non-null    int64
 19  eating_out                    125 non-null    int64
 20  employment                    116 non-null    float64
 21  ethnic_food                   125 non-null    int64
 22  exercise                      112 non-null    float64
 23  father_education              124 non-null    float64
 24  father_profession             122 non-null    str
 25  fav_cuisine                   123 non-null    str
 26  fav_cuisine_coded             125 non-null    int64
 27  fav_food                      123 non-null    float64
 28  food_childhood                124 non-null    str
 29  fries                         125 non-null    int64
 30  fruit_day                     125 non-null    int64
 31  grade_level                   125 non-null    int64
 32  greek_food                    125 non-null    int64
 33  healthy_feeling               125 non-null    int64
 34  healthy_meal                  124 non-null    str
 35  ideal_diet                    124 non-null    str
 36  ideal_diet_coded              125 non-null    int64
 37  income                        124 non-null    float64
 38  indian_food                   125 non-null    int64
 39  italian_food                  125 non-null    int64
 40  life_rewarding                124 non-null    float64
 41  marital_status                124 non-null    float64
 42  meals_dinner_friend           122 non-null    str
 43  mother_education              122 non-null    float64
 44  mother_profession             123 non-null    str
 45  nutritional_check             125 non-null    int64
 46  on_off_campus                 124 non-null    float64
 47  parents_cook                  125 non-null    int64
 48  pay_meal_out                  125 non-null    int64
 49  persian_food                  124 non-null    float64
 50  self_perception_weight        124 non-null    float64
 51  soup                          124 non-null    float64
 52  sports                        123 non-null    float64
 53  thai_food                     125 non-null    int64
 54  tortilla_calories             124 non-null    float64
 55  turkey_calories               125 non-null    int64
 56  type_sports                   99 non-null     str
 57  veggies_day                   125 non-null    int64
 58  vitamins                      125 non-null    int64
 59  waffle_calories               125 non-null    int64
 60  weight                        123 non-null    str
dtypes: float64(20), int64(27), str(14)
memory usage: 59.7 KB

What are the columns and their types in this data set?

In [11]:
# Show the column names and their types.
df_food.dtypes

GPA                     str
Gender                int64
breakfast             int64
calories_chicken      int64
calories_day        float64
                     ...
type_sports             str
veggies_day           int64
vitamins              int64
waffle_calories       int64
weight                  str
Length: 61, dtype: object

### Clean the Data

Perhaps we’d like to know more another day, but the team is really interested in just the relationship between calories (`calories_day`) and weight. …and maybe gender.

Can you remove the other columns?

In [6]:
# Remove ‘em.
columns = ['calories_day', 'weight', 'Gender']
filtered_df = df_food[columns]
filtered_df

     calories_day                    weight  Gender
0             NaN                       187       2
1             3.0                       155       1
2             4.0  I'm not answering this.        1
3             3.0             Not sure, 240       1
4             2.0                       190       1
..            ...                       ...     ...
120           4.0                       156       1
121           2.0                       180       1
122           NaN                       120       1
123           4.0                       135       2
124           NaN                       135       1

[125 rows x 3 columns]

What about `NaN`s? How many are there?

In [7]:
# Count ‘em.

filtered_df.isna().sum()

calories_day    19
weight           2
Gender           0
dtype: int64

We gotta remove those `NaN`s―the entire row.

In [10]:
# Drop ‘em.
clean_df = filtered_df.dropna()
clean_df.info()
clean_df

<class 'pandas.DataFrame'>
Index: 104 entries, 1 to 123
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   calories_day  104 non-null    float64
 1   weight        104 non-null    str
 2   Gender        104 non-null    int64
dtypes: float64(1), int64(1), str(1)
memory usage: 3.2 KB

     calories_day                    weight  Gender
1             3.0                       155       1
2             4.0  I'm not answering this.        1
3             3.0             Not sure, 240       1
4             2.0                       190       1
5             3.0                       190       1
..            ...                       ...     ...
118           3.0                       140       1
119           3.0                       185       2
120           4.0                       156       1
121           2.0                       180       1
123           4.0                       135       2

[104 rows x 3 columns]

But what about the weird non-numeric values in the column obviously meant for numeric data?

Notice the data type of that column from when you got the types of all the columns?

If only we could convert the column to a numeric type and drop the rows with invalid values. 🤔

In [17]:
# Fix that.
cleaner_df = clean_df.apply(pd.to_numeric, errors='coerce')
cleaner_df.value_counts()

calories_day  weight  Gender
3.0           125.0   1         5
              185.0   2         5
              150.0   1         4
              140.0   1         4
              155.0   1         3
                               ..
              138.0   2         1
4.0           150.0   2         1
              156.0   1         1
2.0           180.0   1         1
4.0           135.0   2         1
Name: count, Length: 72, dtype: int64

Now this data seems reasonably clean for our purposes! 😁

Let’s save it somewhere to be shipped off to another teammate. 💾

In [18]:
# Savey save!
filepath = "/workspaces/ds-fall-2026/Week-02-Pandas-and-How-to-Make-a-Sick-Project/data/cleaned.csv"
cleaner_df.to_csv(filepath)

## Ask a Manager Salary Survey 2021 (Responses) Data Set

### Load the Data

In [7]:
# Load the Ask A Manager Salary Survey 2021 (Responses) data set into a variable (e.g., df_salary).
df_salary = pd.read_csv('/workspaces/ds-fall-2026/Week-02-Pandas-and-How-to-Make-a-Sick-Project/data/Ask A Manager Salary Survey 2021 (Responses) - Form Responses 1.tsv', sep='\t')
filepath = "/workspaces/ds-fall-2026/Week-02-Pandas-and-How-to-Make-a-Sick-Project/data/salarysurvey.tsv"
df_salary.to_csv(filepath, sep='\t', index=False)

Was that hard? 🙃

#### rename the file to something that is better for all systems.  
* No spaces in filename (can use '_')
* all lower case

### Explore

You know the drill.

How much data did you just load?

In [2]:
# Count by hand. I’m dead serious.
filepath = "/workspaces/ds-fall-2026/Week-02-Pandas-and-How-to-Make-a-Sick-Project/data/salarysurvey.tsv"
df_salary = pd.read_csv(filepath, sep='\t')
print(f"shape: {df_salary.shape}")
print(f"df_salary.info(): {df_salary.info()}")

shape: (28062, 18)
<class 'pandas.DataFrame'>
RangeIndex: 28062 entries, 0 to 28061
Data columns (total 18 columns):
 #   Column                                                                                                                                                                                                                                Non-Null Count  Dtype
---  ------                                                                                                                                                                                                                                --------------  -----
 0   Timestamp                                                                                                                                                                                                                             28062 non-null  str
 1   How old are you?                                                                                                                                                                                                                      28062 non-null  str
 2   What industry do you work in?                                                                                                                                                                                                         27988 non-null  str
 3   Job title                                                                                                                                                                                                                             28061 non-null  str
 4   If your job title needs additional context, please clarify here:                                                                                                                                                                      7262 non-null   str
 5   What is your annual salary? (You'll indicate the currency in a later question. If you are part-time or hourly, please enter an annualized equivalent -- what you would earn if you worked the job 40 hours a week, 52 weeks a year.)  28062 non-null  str
 6   How much additional monetary compensation do you get, if any (for example, bonuses or overtime in an average year)? Please only include monetary compensation here, not the value of benefits.                                        20766 non-null  float64
 7   Please indicate the currency                                                                                                                                                                                                          28062 non-null  str
 8   If "Other," please indicate the currency here:                                                                                                                                                                                        206 non-null    str
 9   If your income needs additional context, please provide it here:                                                                                                                                                                      3042 non-null   str
 10  What country do you work in?                                                                                                                                                                                                          28062 non-null  str
 11  If you're in the U.S., what state do you work in?                                                                                                                                                                                     23039 non-null  str
 12  What city do you work in?                                                                                                                                                                                                             27980 non-null  str
 13  How many years of professional work experience do you have overall?                                                                                                                                                                   28062 non-null  str
 14  How many years of professional work experience do you have in your field?                                                                                                                                                             28062 non-null  str
 15  What is your highest level of education completed?                                                                                                                                                                                    27840 non-null  str
 16  What is your gender?                                                                                                                                                                                                                  27891 non-null  str
 17  What is your race? (Choose all that apply.)                                                                                                                                                                                           27885 non-null  str
dtypes: float64(1), str(17)
memory usage: 3.9 MB
df_salary.info(): None

What are the columns and their types?

In [17]:
# Show the column names and their types.

print(df_salary.dtypes)

Timestamp                                                                                                                                                                                                                                   str
How old are you?                                                                                                                                                                                                                            str
What industry do you work in?                                                                                                                                                                                                               str
Job title                                                                                                                                                                                                                                   str
If your job title needs additional context, please clarify here:                                                                                                                                                                            str
What is your annual salary? (You'll indicate the currency in a later question. If you are part-time or hourly, please enter an annualized equivalent -- what you would earn if you worked the job 40 hours a week, 52 weeks a year.)        str
How much additional monetary compensation do you get, if any (for example, bonuses or overtime in an average year)? Please only include monetary compensation here, not the value of benefits.                                          float64
Please indicate the currency                                                                                                                                                                                                                str
If "Other," please indicate the currency here:                                                                                                                                                                                              str
If your income needs additional context, please provide it here:                                                                                                                                                                            str
What country do you work in?                                                                                                                                                                                                                str
If you're in the U.S., what state do you work in?                                                                                                                                                                                           str
What city do you work in?                                                                                                                                                                                                                   str
How many years of professional work experience do you have overall?                                                                                                                                                                         str
How many years of professional work experience do you have in your field?                                                                                                                                                                   str
What is your highest level of education completed?                                                                                                                                                                                          str
What is your gender?                                                                                                                                                                                                                        str
What is your race? (Choose all that apply.)                                                                                                                                                                                                 str
dtype: object

Oh… Ugh! Give these columns easier names to work with first. 🙄

In [3]:
# Rename ‘em.
# Non-binding suggestions: timestamp, age, industry, title, title_context, salary, additional_compensation, currency, other_currency, salary_context, country, state, city, total_yoe, field_yoe, highest_education_completed	gender, race
old_column_names = df_salary.columns.tolist()
new_column_names = ['timestamp', 'age', 'industry', 'title', 'title_context', 'salary', 'additional_compensation', 'currency', 'other_currency', 'salary_context', 'country', 'state', 'city', 'total_yoe', 'field_yoe', 'highest_education_completed', 'gender', 'race']
updatedNames = dict(zip(old_column_names, new_column_names))
df_new_salary = df_salary.rename(columns = updatedNames)
print(df_new_salary.head())

            timestamp    age                       industry  \
0  4/27/2021 11:02:10  25-34   Education (Higher Education)
1  4/27/2021 11:02:22  25-34              Computing or Tech
2  4/27/2021 11:02:38  25-34  Accounting, Banking & Finance
3  4/27/2021 11:02:41  25-34                     Nonprofits
4  4/27/2021 11:02:42  25-34  Accounting, Banking & Finance

                                      title title_context  salary  \
0        Research and Instruction Librarian           NaN  55,000
1  Change & Internal Communications Manager           NaN  54,600
2                      Marketing Specialist           NaN  34,000
3                           Program Manager           NaN  62,000
4                        Accounting Manager           NaN  60,000

   additional_compensation currency other_currency salary_context  \
0                      0.0      USD            NaN            NaN
1                   4000.0      GBP            NaN            NaN
2                      NaN      USD            NaN            NaN
3                   3000.0      USD            NaN            NaN
4                   7000.0      USD            NaN            NaN

          country           state         city     total_yoe    field_yoe  \
0   United States   Massachusetts       Boston     5-7 years    5-7 years
1  United Kingdom             NaN    Cambridge  8 - 10 years    5-7 years
2              US       Tennessee  Chattanooga   2 - 4 years  2 - 4 years
3             USA       Wisconsin    Milwaukee  8 - 10 years    5-7 years
4              US  South Carolina   Greenville  8 - 10 years    5-7 years

  highest_education_completed      gender   race
0             Master's degree       Woman  White
1              College degree  Non-binary  White
2              College degree       Woman  White
3              College degree       Woman  White
4              College degree       Woman  White

It’s a lot, and that should not have been easy. 😏

You’re going to have a gander at the computing/tech subset first because thats *your* industry. But first, what value corresponds to that `industry`?

In [ ]:
# List the unique industries and a count of their instances.

df_new_salary['industry'].value_counts()

# Computing or Tech

industry
Computing or Tech                               4699
Education (Higher Education)                    2464
Nonprofits                                      2419
Health care                                     1896
Government and Public Administration            1889
                                                ...
Undergrad student                                  1
Concrete Construction                              1
I'm currently a student and don't have a job       1
Student                                            1
Wine & Spirits                                     1
Name: count, Length: 1219, dtype: int64

That value among the top 5 is what you’re looking for innit? Filter out all the rows not in that industry and save it into a new dataframe.

In [4]:
# Filtery filter. (Save it to a new variable, df_salary_tech.)
cond = df_new_salary['industry'] == 'Computing or Tech'
df_salary_tech = df_new_salary[cond].copy()
df_salary_tech

,timestamp,age,industry,title,title_context,salary,additional_compensation,currency,other_currency,salary_context,country,state,city,total_yoe,field_yoe,highest_education_completed,gender,race
1,4/27/2021 11:02:22,25-34,Computing or Tech,Change & Internal Communications Manager,NaN,"54,600",4000.0,GBP,NaN,NaN,United Kingdom,NaN,Cambridge,8 - 10 years,5-7 years,College degree,Non-binary,White
8,4/27/2021 11:03:01,45-54,Computing or Tech,Systems Analyst,Data developer/ETL Developer,"112,000",10000.0,USD,NaN,NaN,US,Missouri,St. Louis,21 - 30 years,21 - 30 years,College degree,Woman,White
43,4/27/2021 11:04:04,25-34,Computing or Tech,Principal Software Engineer,NaN,"187,500",5000.0,USD,NaN,NaN,United States,Pennsylvania,Pittsburgh,8 - 10 years,5-7 years,College degree,Woman,White
44,4/27/2021 11:04:04,25-34,Computing or Tech,Intelligence Analyst,NaN,"110,000",20000.0,USD,NaN,"Around 20,000 a year in stock",USA,Virginia,"Arlington, VA",8 - 10 years,8 - 10 years,Master's degree,Man,White
46,4/27/2021 11:04:07,35-44,Computing or Tech,Mobile developer,NaN,"144,600",2500.0,USD,NaN,NaN,USA,Massachusetts,Boston,5-7 years,5-7 years,PhD,Woman,White
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28050,7/1/2024 13:38:46,25-34,Computing or Tech,Research & Systems Technician Data Analytics,NaN,22000,NaN,EUR,NaN,NaN,Spain,NaN,Barcelona,2 - 4 years,2 - 4 years,College degree,Man,"Hispanic, Latino, or Spanish origin"
28051,7/1/2024 20:05:58,25-34,Computing or Tech,Junior data analyst,NaN,35000,15000.0,USD,NaN,NaN,Usa,Alabama,Alabama,2 - 4 years,2 - 4 years,College degree,Woman,Black or African American
28052,7/3/2024 14:02:01,25-34,Computing or Tech,Senior Global Public Relations Manager,NaN,144000,15000.0,USD,NaN,NaN,Usa,Massachusetts,Boise-but remote. Company located in Boston,8 - 10 years,8 - 10 years,Master's degree,Woman,White
28058,7/23/2024 17:51:03,25-34,Computing or Tech,Systems Architect,NaN,109000,NaN,USD,NaN,NaN,USA,Georgia,Atlanta,5-7 years,5-7 years,College degree,Man,White
28060,7/26/2024 11:20:45,18-24,Computing or Tech,IT,NaN,1700,10.0,USD,NaN,NaN,Burma,NaN,Yangon,2 - 4 years,1 year or less,Some college,Man,Asian or Asian American

Do a sanity check to make sure that the only values you kept are the one you are filtered for.

In [16]:
# Sanity Check 

df_salary_tech.value_counts()

timestamp          age    industry           title  title_context  salary  additional_compensation  currency  other_currency  salary_context  country  state     city  total_yoe  field_yoe      highest_education_completed  gender  race
2/6/2024 21:15:28  18-24  Computing or Tech  sdsd   ds             4       22.0                     USD       1               dd              ss       Arkansas  s     5-7 years  11 - 20 years  Some college                 Man     Black or African American    1
Name: count, dtype: int64

+3.1LLLLLL          ZxcWe are very interested in salary figures. But how many dollars 💵 is a euro 💶 or a pound 💷? That sounds like a problem for another day. 🫠

For now, let’s just look at U.S. dollars (`'USD'`).

In [5]:
# Filtery filter for just the jobs that pay in USD!

cond = df_salary_tech['currency'] == 'USD'
USD_df = df_salary_tech[cond].copy()

What we really want know is how each U.S. city pays in tech. What value in `country` represents the United States of America?

In [21]:
# We did filter for USD, so if we do a count of each unique country in descending count order, the relevant value(s) should show up at the top.

USD_df['country'].value_counts()

country
United States               1576
USA                         1222
US                           412
U.S.                         108
United States of America      90
                            ...
Ghana                          1
Nigeria                        1
ss                             1
Nigeria                        1
Burma                          1
Name: count, Length: 76, dtype: int64

### Clean the Data

Well, we can’t get our answers with what we currently have, so you’ll have to make some changes.

Let’s not worry about anything below the first 5 values for now. Convert the top 5 to a single canonical value―say, `'US'`, which is nice and short.

In [27]:
# Replace them all with 'US'.

normalized_df = USD_df['country'].copy().str.strip().str.lower().str.replace(' ', '', regex=False).str.replace('\'', '', regex=False).str.replace('.', '', regex=False)
USSpellings = normalized_df.value_counts().head(4).index.to_list()
USSpellings.extend(['unitedstateofamerica', 'unitestates', 'uniyedstates', 'america', 'unitedstate', 'unitedstateds', 'unitedstated', 'unitedstares', 'unitesstates'])
normalizedMaskDF = normalized_df.isin(USSpellings)
# create a copy, incase I botch something.
normalizedUSDdf = USD_df.copy()
normalizedUSDdf['country'] = np.where(normalizedMaskDF, 'US', USD_df['country'])
normalizedUSDdf['country'].value_counts()

country
US                      3723
Israel                     5
Canada                     4
Australia                  2
India                      2
Spain                      2
Brazil                     2
United Kingdom             2
New Zealand                2
Poland                     2
France                     2
Puerto Rico                1
Cuba                       1
Danmark                    1
Italy                      1
International              1
Remote (philippines)       1
Singapore                  1
Uruguay                    1
Mexico                     1
Canada                     1
ISA                        1
singapore                  1
Pakistan                   1
Netherlands                1
China                      1
San Francisco              1
Romania                    1
Japan                      1
Australian                 1
Denmark                    1
Jamaica                    1
Thailand                   1
Colombia                   1
denmark                    1
Ghana                      1
Nigeria                    1
ss                         1
Nigeria                    1
Burma                      1
Name: count, dtype: int64

Have a look at the count of each unique country again now.

In [29]:
# Count again.
normalizedUSDdf['country'].value_counts()

country
US                      3723
Israel                     5
Canada                     4
Australia                  2
India                      2
Spain                      2
Brazil                     2
United Kingdom             2
New Zealand                2
Poland                     2
France                     2
Puerto Rico                1
Cuba                       1
Danmark                    1
Italy                      1
International              1
Remote (philippines)       1
Singapore                  1
Uruguay                    1
Mexico                     1
Canada                     1
ISA                        1
singapore                  1
Pakistan                   1
Netherlands                1
China                      1
San Francisco              1
Romania                    1
Japan                      1
Australian                 1
Denmark                    1
Jamaica                    1
Thailand                   1
Colombia                   1
denmark                    1
Ghana                      1
Nigeria                    1
ss                         1
Nigeria                    1
Burma                      1
Name: count, dtype: int64

Did you notice anything interesting?

In [ ]:
# BONUS CREDIT: resolve [most of] those anomalous cases too without exhaustively taking every variant literally into account.

# did it above

In [30]:

# BONUS CREDIT: if you’ve resolved it, let’s see how well you did by counting the number of instances of each unique value.

normalizedUSDdf.head(5)

,timestamp,age,industry,title,title_context,salary,additional_compensation,currency,other_currency,salary_context,country,state,city,total_yoe,field_yoe,highest_education_completed,gender,race
8,4/27/2021 11:03:01,45-54,Computing or Tech,Systems Analyst,Data developer/ETL Developer,"112,000",10000.0,USD,NaN,NaN,US,Missouri,St. Louis,21 - 30 years,21 - 30 years,College degree,Woman,White
43,4/27/2021 11:04:04,25-34,Computing or Tech,Principal Software Engineer,NaN,"187,500",5000.0,USD,NaN,NaN,US,Pennsylvania,Pittsburgh,8 - 10 years,5-7 years,College degree,Woman,White
44,4/27/2021 11:04:04,25-34,Computing or Tech,Intelligence Analyst,NaN,"110,000",20000.0,USD,NaN,"Around 20,000 a year in stock",US,Virginia,"Arlington, VA",8 - 10 years,8 - 10 years,Master's degree,Man,White
46,4/27/2021 11:04:07,35-44,Computing or Tech,Mobile developer,NaN,"144,600",2500.0,USD,NaN,NaN,US,Massachusetts,Boston,5-7 years,5-7 years,PhD,Woman,White
47,4/27/2021 11:04:09,35-44,Computing or Tech,Product Design Director,NaN,"200,850",40000.0,USD,NaN,NaN,US,North Carolina,Chapel Hill,11 - 20 years,11 - 20 years,College degree,Woman,White

It’s looking good so far. Let’s find out the minimum, mean, and maximum (in that order) salary by state, sorted by the mean in descending order.

In [39]:
# Find the minimum, mean, and maximum salary in USD by U.S. state.
USMask = normalizedUSDdf['country'] == 'US'

# keep only rows with 'US'
USDF = normalizedUSDdf[USMask]

# group by states
groupedStates = USDF.groupby('state')

# think this is the part where the non-numeric field bites me in the keester.
groupedStates['salary'].agg(['min', 'max', 'mean'])

TypeError: dtype 'str' does not support operation 'mean'

Well, pooh! We forgot that `salary` isn’t numeric. Something wrong must be fixed.

In [ ]:
# Fix it.
normalizedSalary = USDF['salary'].str.replace(',', '', regex=False)
numericUSDF = USDF.copy()
numericUSDF['salary'] = pd.to_numeric(normalizedSalary, errors='coerce')
numericUSDF['salary'].value_counts()

salary
120000     95
130000     94
150000     86
110000     85
90000      77
           ..
170420      1
45109       1
116421      1
101150      1
2600000     1
Name: count, Length: 686, dtype: int64

Let’s try that again.

In [63]:
# Try it again. Yeah!

USMask = numericUSDF['country'] == 'US'
USOnlyDF = numericUSDF[USMask]

aggResults = USOnlyDF.groupby('state')['salary'].agg(['min', 'mean', 'max'])
aggResults.sort_values('mean', ascending=False)

                                min           mean      max
state
Michigan, Texas, Washington  340000  340000.000000   340000
California, Oregon           200000  200000.000000   200000
California, Colorado         176000  176000.000000   176000
Georgia, Massachusetts       175000  175000.000000   175000
Florida                       28800  157457.232143  2600000
...                             ...            ...      ...
Louisiana                     35360   83269.090909   150000
Massachusetts, Pennsylvania   83000   83000.000000    83000
Arkansas                      55000   81682.300000   144000
California, Maryland          81500   81500.000000    81500
Alabama, Montana              72000   72000.000000    72000

[66 rows x 3 columns]

That did the trick! Now let’s narrow this to data 2021 and 2022 just because (lel). *(Hint: that timestamp column may not be a temporal type right now.)*

In [69]:
# Filter the data to within 2021, 2022, or 2023, saving the DataFrame to a new variable, and generate the summary again.

datedDF = USOnlyDF.copy()
datedDF['timestamp'] = pd.to_datetime(datedDF['timestamp'])
yearMask = datedDF['timestamp'].dt.year.isin([2021,2022])
datedDF = datedDF[yearMask]
datedDF['timestamp'].dt.year.value_counts()

timestamp
2021    3663
2022      39
Name: count, dtype: int64

## Bonus

Clearly, we do not have enough data to produce useful figures for the level of specificity you’ve now reached. What do you notice about Delaware and West Virginia?

Let’s back out a bit and return to `df_salary` (which was the loaded data with renamed columns but *sans* filtering).

### Bonus #0

Apply the same steps as before to `df_salary`, but do not filter for any specific industry. Do perform the other data cleaning stuff, and get to a point where you can generate the minimum, mean, and maximum by state.

### Bonus #1

This time, format the table output nicely (*$12,345.00*) without modifying the values in the `DataFrame`. That is, `df_salary` should be identical before versus after running your code.

(*Hint: if you run into an error about `jinja2` perhaps you need to `pip install` something.*)

### Bonus #2

Filter out the non-single-states (e.g., `'California, Colorado'`) in the most elegant way possible (i.e., *not* by blacklisting all the bad values).

### Bonus #3

Show the quantiles instead of just minimum, mean, and maximum―say 0%, 5%, 25%, 50%, 75%, 95%, and 100%. Outliers may be deceiving.

Sort by whatever interests you―like say the *50th* percentile.

And throw in a count by state too. It would be interesting to know how many data points contribute to the figures for each state. (*Hint: your nice formatting from Bonus #1 might not work this time around.* 😜)